# fly.toml app configuration file generated for string-analyzer-api-hng13 on 2025-10-22T01:12:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'string-analyzer-api-hng13'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
